## FOLDERS
BASE_FOLDER_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_FOLDER_PATH="${BASE_FOLDER_PATH}/logs"
MODULES_FOLDER_PATH="${BASE_FOLDER_PATH}/modules"
mkdir -p "$LOG_FOLDER_PATH"
mkdir -p "$MODULES_FOLDER_PATH"